#!/usr/bin/env bash
set -euo pipefail

tool="${1:-}"

if [[ -z "${tool}" ]]; then
    printf '%s\n' "Usage: ./build.sh <codex|copilot|gemini|rovo>" >&2
    exit 2
fi

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
canonical="${root}/canonical"
build="${root}/build/${tool}"

if [[ ! -d "${canonical}" ]]; then
    printf '%s\n' "Missing canonical directory: ${canonical}" >&2
    exit 1
fi

rm -rf "${build}"
mkdir -p "${build}"

write_section() {
    local title="${1}"
    local file="${2}"

    if [[ -f "${file}" ]]; then
        {
            printf '\n\n'
            printf '# %s\n\n' "${title}"
            cat "${file}"
        } >> "${build}/AGENTS.md"
    fi
}

copy_skills() {
    local skill_dir
    local skill_name

    mkdir -p "${build}/skills"

    for skill_dir in "${canonical}/skills"/*; do
        [[ -d "${skill_dir}" ]] || continue

        skill_name="$(basename "${skill_dir}")"

        if [[ -f "${skill_dir}/SKILL.md" ]]; then
            mkdir -p "${build}/skills/${skill_name}"
            cp "${skill_dir}/SKILL.md" "${build}/skills/${skill_name}/SKILL.md"
        fi
    done
}

copy_support_dir() {
    local name="${1}"

    if [[ -d "${canonical}/${name}" ]]; then
        mkdir -p "${build}/${name}"
        cp -R "${canonical}/${name}/." "${build}/${name}/"
    fi
}

copy_packets() {
    mkdir -p "${build}/packets"
    cp "${canonical}/packets/"*.md "${build}/packets/"
}

copy_copilot_files() {
    cp "${canonical}/bootstrap/copilot.md" "${build}/BOOTSTRAP.md"
    cp "${canonical}/tool-profiles/copilot.md" "${build}/tool-profile.md"
}

{
    printf '# Agentic Harness\n\n'
    printf 'This file is generated from canonical harness definitions.\n\n'
    printf 'Do not edit this file directly. Edit files under canonical/ instead.\n\n'
} > "${build}/AGENTS.md"

write_section "Strategy" "${canonical}/strategy.md"
write_section "State Machine" "${canonical}/state/state-machine.md"
write_section "Skill Assignment" "${canonical}/skills/skill-assignment.md"

for file in "${canonical}/commands"/*.md; do
    [[ -f "${file}" ]] || continue
    write_section "Command: $(basename "${file}" .md)" "${file}"
done

for file in "${canonical}/agents"/*/AGENTS.md; do
    [[ -f "${file}" ]] || continue
    agent_name="$(basename "$(dirname "${file}")")"
    write_section "Agent: ${agent_name}" "${file}"
done

for file in "${canonical}/schemas"/*.md; do
    [[ -f "${file}" ]] || continue
    write_section "Schema: $(basename "${file}" .md)" "${file}"
done

for file in "${canonical}/templates"/*.md; do
    [[ -f "${file}" ]] || continue
    write_section "Template: $(basename "${file}" .md)" "${file}"
done

case "${tool}" in
    codex|copilot|gemini|rovo)
        copy_skills
        copy_packets
        ;;
    *)
        printf '%s\n' "Unsupported tool: ${tool}" >&2
        exit 2
        ;;
esac

if [[ "${tool}" == "copilot" ]]; then
    copy_copilot_files
fi

copy_support_dir "agents"
copy_support_dir "commands"
copy_support_dir "schemas"
copy_support_dir "templates"
copy_support_dir "state"

printf 'Built harness for %s: %s\n' "${tool}" "${build}"
